---

- hosts: all
  become: true

  vars:
    flask_user: flask

  tasks:
  
  - name: create project user
    user:
      name: "{{ flask_user }}"
      state: present
      shell: /bin/bash


  - name: create project folder
    file:
      path: "/home/{{ flask_user }}/base/app"
      state: directory


  - name: install packages
    apt:
      state: present
      name: "{{ item }}"
    with_items:
    - python3-venv
    
    
  - name: create virtualenv
    command: "python3 -m venv /home/{{ flask_user }}/base/venv"
    args:
      creates: "/home/{{ flask_user }}/base/venv"

    
  - name: install modules a virtualenv
    pip:
      requirements: "/home/{{ flask_user }}/base/requirements.txt"
      virtualenv: "/home/{{ flask_user }}/base/venv"
      virtualenv_python: "python3"

